# Generated by Django 5.0.4 on 2024-04-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Friends',
        ),
    ]
