# Generated by Django 5.0.4 on 2024-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customuser_icon_alter_friends_friends_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
    ]
