# Generated by Django 5.0.4 on 2024-05-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser_friends_customuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
